[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 120
restartPolicyType = "always"

[[services]]
name = "soldegen-frontend"
port = 3000